exp_taste/users/urls.py
from django.urls import path

from exp_taste.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

feedback/urls.py
from django.urls import path
from django.views.generic import TemplateView

import feedback.views as views

app_name = "feedback"

urlpatterns = [
    path("", 
         views.submit_feedback,
         name="form"),
    path("thankyou",
        TemplateView.as_view(template_name="feedback/thankyou.html"), 
        name="thankyou"),
    path("list",
         views.FeedbackList.as_view(),
         name="list"),
    path("detail/<uuid:pk>",
         views.FeedbackDetail.as_view(),
         name="detail"),
     path('export/excel',
          views.to_excel,
          name="export_excel")
]

main/urls.py
from django.urls import path

import main.views as views

app_name = "main"

urlpatterns = [
    path("", 
         views.Home.as_view(),
         name="home"),
    path("about/",
         views.about,
         name="about")
]

exp_taste/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

import pytz

class User(AbstractUser):
    """Default user for Expensive Taste."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    timezone = CharField(
        "Preferred Time Zone",
        max_length=30,
        choices=((tz, tz) for tz in pytz.common_timezones),
        default="UTC"
    )

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

exp_taste/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from django import forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

exp_taste/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

exp_taste/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name", "timezone"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

exp_taste/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Expensive Taste{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Expensive Taste - Choose the most expensive artwork">
    <meta name="author" content="Gabriel Getzie">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicons/site.webmanifest' %}">

    {% block css %}
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block extra_head %}{% endblock extra_head %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'main:home' %}">Expensive Taste</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == '/' %}active{% endif %}">
              <a class="nav-link" href="{% url 'main:home' %}">
                Home {% if request.path == '/'%}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item {% if 'about' in request.path  %}active{% endif %}">
              <a class="nav-link" href="{% url 'main:about' %}">
                About{% if 'about' in request.path %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item {% if 'feedback' in request.path  %}active{% endif %}">
              <a class="nav-link" href="{% url 'feedback:form' %}">
                Feedback {% if 'feedback' in request.path %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item {% if '/users' in request.path or '/accounts' in request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'users:detail' request.user.username %}">
                Profile{% if '/users' in request.path or '/accounts' in request.path %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            {% endif %}
            
            {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
            </li>
            {% endif %}
          </ul>
          {% if request.user.is_authenticated %}
          
          <a class="btn btn-secondary" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          {% endif %}
          
        </div>
      </nav>

    </div>

    <div id="main" class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        
      {% endblock content %}

    </div> <!-- /container -->

    <footer class="bg-light mt-3">
      <div class="container text-center">
	      <small>Developed by <a href="https://kotsf.com">KotSF</a> with <a href="https://msteinberg.art">Monica Steinberg</a></small>
      </div>
    </footer>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Vendor dependencies bundled as one file-->
      <script src="{% static 'js/vendors.min.js' %}"></script>


      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.min.js' %}"></script>

    {% endblock javascript %}
    {% block more_js %}
    
    {% endblock more_js %}
    <script async defer src="https://sa.expensivetaste.art/latest.js"></script>
    <noscript><img src="https://sa.expensivetaste.art/noscript.gif" alt=""/></noscript>
  </body>
</html>
 