exp_taste/users/urls.py
from django.urls import path

from exp_taste.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

feedback/urls.py
from django.urls import path
from django.views.generic import TemplateView

import feedback.views as views

app_name = "feedback"

urlpatterns = [
    path("", 
         views.submit_feedback,
         name="form"),
    path("thankyou",
        TemplateView.as_view(template_name="feedback/thankyou.html"), 
        name="thankyou"),
    path("list",
         views.FeedbackList.as_view(),
         name="list"),
    path("detail/<uuid:pk>",
         views.FeedbackDetail.as_view(),
         name="detail"),
     path('export/excel',
          views.to_excel,
          name="export_excel")
]

main/urls.py
from django.urls import path

import main.views as views

app_name = "main"

urlpatterns = [
    path("", 
         views.Home.as_view(),
         name="home"),
    path("about/",
         views.about,
         name="about")
]

exp_taste/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

import pytz

class User(AbstractUser):
    """Default user for Expensive Taste."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    timezone = CharField(
        "Preferred Time Zone",
        max_length=30,
        choices=((tz, tz) for tz in pytz.common_timezones),
        default="UTC"
    )

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

feedback/models.py
import datetime
import uuid

import markdown

from django.db import models

def utc_now():
    return datetime.datetime.now(tz=datetime.timezone.utc)


class Feedback(models.Model):
    id = models.UUIDField("id", primary_key=True, default=uuid.uuid4)
    name = models.CharField("Name", max_length=150, default="", blank=True)
    email = models.EmailField("Email", default="", blank=True)
    location = models.CharField("Location", max_length=200, default="")
    created = models.DateTimeField("Timestamp", default=utc_now)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return str(self.created)


class Question(models.Model):
    class QuestionTypes(models.IntegerChoices):
        FREE_RESPONSE = 1
        MULTIPLE_CHOICE = 2
        
    text = models.TextField("Question")
    active = models.BooleanField("Active", default=True)
    qtype = models.PositiveSmallIntegerField("Question Type", 
                                             choices=QuestionTypes.choices,
                                             default=1)
    order = models.PositiveSmallIntegerField("Order", default=1)
    required = models.BooleanField("Required", default=True)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return self.text[:20]


class MultiChoiceOption(models.Model):
    order = models.PositiveSmallIntegerField("Order", default=1)
    text2 = models.CharField("Text", max_length=280, default="")
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    weight = models.IntegerField("Weight", default=0)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return self.text2[:20]


class Response(models.Model):
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField("Free Response", default="", blank=True)
    selected = models.ForeignKey(
        MultiChoiceOption, 
        on_delete=models.CASCADE,
        blank=True, null=True)

    class Meta:
        ordering = ["question__order"]

class FreeResponse(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    response = models.TextField("Response")
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)


class MultiChoiceResponse(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected = models.ForeignKey(MultiChoiceOption, on_delete=models.CASCADE)
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)


class PageCopy(models.Model):
    text = models.TextField("Text")
    current = models.BooleanField("Current", default=True)

    class Meta:
        verbose_name = "Feedback Page Intro"

    def __str__(self):
        return self.text[:20]

    @property
    def html(self):
        return markdown.markdown(self.text)
            

exp_taste/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from django import forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

feedback/forms.py
import logging

from django import forms
from django.conf import settings
from django.forms.widgets import RadioSelect, Textarea


from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Field, Div

from feedback.models import Question, Response, Feedback
from feedback.utils import verify_captcha

logger = logging.getLogger(__name__)

class MCOModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.text2

class ActiveQuestionsForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "feedback-form"
        self.helper.form_method = "POST"
        self.helper.form_action = "."
        self.helper.label_class = "question"
        questions = Question.objects.filter(active=True)
        for question in questions:
            field_label = f"{question.order}. {question.text}"
            if question.qtype == 1:
                field = forms.CharField(
                    max_length=5000, 
                    label=field_label,
                    required=question.required,
                    widget=Textarea(attrs={"rows": 1}))
            elif question.qtype == 2:
                options = question.multichoiceoption_set.all()
                field = MCOModelChoiceField(
                    queryset=options,
                    label=field_label,
                    required=question.required,
                    widget=RadioSelect
                )
            self.fields[f"question_{question.id}"] = field
        self.helper.layout = Layout(
            *(Field(key) for key in self.fields.keys()),
            Div(css_class="g-recaptcha",
                data_sitekey=settings.RECAPTCHA_SITE,
                data_callback="enableSubmit",
                data_expired_callback="captchaExpired"),
            Div(
                Submit(
                    'submit', 
                    'Submit', 
                    css_class="btn btn-primary", 
                    disabled=True,
                    id='feedback-submit'),
                css_class="form-group d-flex flex-row-reverse"
            )
        )

    def clean(self):
        cleaned_data = super().clean()
        token = self.request.POST.get("g-recaptcha-response", None)
        captcha = verify_captcha(token)
        if not captcha.get('success', False):
            raise forms.ValidationError("Captcha Failed")
        if not any(cleaned_data.values()):
            raise forms.ValidationError("Please answer at least one question")
        return cleaned_data

    def save(self):
        feedback = Feedback()
        feedback.save()
        for key, value in self.cleaned_data.items():
            if not key.startswith("question_"): 
                continue
            q_id = key.split("_")[1]
            question = Question.objects.get(id=q_id)
            response = Response(feedback=feedback, question=question)
            if question.qtype == 1:
                response.text = value
            elif question.qtype == 2:
                response.selected = value
            response.save()
        
                

exp_taste/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

exp_taste/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name", "timezone"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

feedback/views.py
import logging
from tempfile import NamedTemporaryFile
from django.http.response import HttpResponse

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import FileResponse

from feedback.models import (
    PageCopy, 
    Feedback, 
    utc_now
    )
from feedback.forms import ActiveQuestionsForm
from feedback.utils import feedback_to_excel

logger = logging.getLogger(__name__)

def submit_feedback(request):
    intro = "We're working on some feedback questions. Please check again soon!"
    try:
        copy = PageCopy.objects.filter(current=True)[0]
        intro = copy.html
    except IndexError:
        pass
    
    if request.POST:
        data = request.POST.copy()
        form = ActiveQuestionsForm(data, request=request)
        if form.is_valid():
            form.save()        
            return redirect("feedback:thankyou")
    else:
        form = ActiveQuestionsForm(request=request)
    context = {
        "intro": intro,
        "form": form,
    }
    return render(request, "feedback/form.html", context=context)

class FeedbackList(LoginRequiredMixin, ListView):
    model = Feedback
    template_name = "feedback/list.html"
    paginate_by = 25
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total"] = Feedback.objects.count()
        return context


class FeedbackDetail(LoginRequiredMixin, DetailView):
    model = Feedback
    template_name = "feedback/detail.html"
    

@login_required
def to_excel(request):
    ts = utc_now().isoformat()
    filename = f"ExpTaste_Feedback_{ts}.xlsx"
    wb = feedback_to_excel(Feedback.objects.all())
    tmp = NamedTemporaryFile()
    wb.save(tmp.name)
    tmp.seek(0)
    response = HttpResponse(tmp.read())
    response["Content-Type"] = "application/vnd.ms-excel"
    response["Content-Disposition"] = f"attachment; filename={filename}"
    return response

exp_taste/templates/feedback/detail.html
{% extends 'base.html' %} {% load tz %} {% block content %}
<h2>Responses</h2>
<p>
  <a href="{% url 'feedback:list' %}"><small>« back to feedback list</small></a>
</p>

<dl class="row">
  <dt class="col-sm-1">Received:</dt>
  {% timezone request.user.timezone %}
  <dd class="col-sm-11">
    {{ object.created|date:'D M j, Y' }} at {{ object.created|time:'g:i:s A e' }}
  </dd>
  {% endtimezone %}
</dl>

{% for response in object.response_set.all %}
<div class="mb-4" style="max-width: 40rem">
  <h3>Question {{ response.question.order }}</h3>
  <p>{{ response.question.text }}</p>
  {% if response.question.qtype == 1 %}
  <p>
    <strong>Response:</strong> {{ response.text|default:"No Response"|wordwrap:40 }}
  </p>
  {% elif response.question.qtype == 2 %}
  <ul class="list-group">
    {% for option in response.question.multichoiceoption_set.all %}
    <li class="list-group-item {% if option.id == response.selected.id %}active{% endif %}">
      {{ option.text2 }}
    </li>
    {% endfor %} {% if not response.selected %}
    <li class="list-group-item active">No Response</li>
    {% endif %}
  </ul>
  {% endif %}
</div>
{% endfor %} {% endblock content %}

exp_taste/templates/feedback/form.html
{% extends "base.html" %}
{% load static crispy_forms_tags %}

{% block content %}
<div style="max-width: 640px; margin: 0 auto;">
    <div class="intro">
        {{ intro|safe }}
    </div>
    {% if request.user.is_authenticated %}
    <p>
        <a href="{% url 'feedback:list' %}">View Feedback</a>
    </p>
    {% endif %}
        
    <div class="question_form">
        {% crispy form %}
    </div>
    
</div>
{% endblock content %}

{% block more_js %}
<script src="{% static 'js/feedback.js' %}"></script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
 {% endblock more_js %}

exp_taste/templates/feedback/list.html
{% extends 'base.html' %} 
{% load feedback_extra %} 
{% load tz %} 
{% block content %}
<h2>Feedback</h2>
<p>
  <a href="{% url 'feedback:export_excel' %}">Export to Excel</a>
</p>
<p>{{ total }} feedback response{{total|pluralize}} received.</p>
<ul class="list-group mb-5" style="max-width: 40rem">
  {% for feedback in page_obj %}
  <li class="list-group-item">
    <a href="{% url 'feedback:detail' feedback.id %}">
      {% timezone request.user.timezone %} 
        {{ feedback.created|date:'D M j, Y'}} at {{ feedback.created|time:'g:i:s A e' }} 
      {% endtimezone %}
    </a>
  </li>
  {% empty %}
  <li class="list-group-item">No feedback yet</li>
  {% endfor %}
</ul>
<nav aria-label="page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; first</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
        </li>
    {% endif %} 
    {% for page_number in page_obj.number|page_window:page_obj.paginator.num_pages %}
        <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }} {% if page_number == page_obj.number %} of 
                {{ page_obj.paginator.num_pages }} {% endif %}
            </a>
        </li>
    {% endfor %} 
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        </li>
    {% endif %}
  </ul>
</nav>
{% endblock content %}

exp_taste/templates/feedback/thankyou.html
{% extends "base.html" %}

{% block content %}
<h2>Thank you!</h2>
<p>We appreciate your feedback</p>
{% endblock content %}